micronaut:
  application:
    name: wordApp
  server:
    cors:
      enabled: true
    port: 8080
    netty:
      log-level: TRACE
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages: 'co.incubyte.wordapp'